// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyL7ztnq4JiE8r9m4QcfiLpMtJAV_CDbg',
    appId: '1:14399025694:web:e6662df267b8413e54b40f',
    messagingSenderId: '14399025694',
    projectId: 'fare-payment-system',
    authDomain: 'fare-payment-system.firebaseapp.com',
    storageBucket: 'fare-payment-system.appspot.com',
    measurementId: 'G-B6ME90G57Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKSLQNLZlsyITpaxI2a3Z5SXHZrej-3Y',
    appId: '1:14399025694:android:a8c30fcc58cea39454b40f',
    messagingSenderId: '14399025694',
    projectId: 'fare-payment-system',
    storageBucket: 'fare-payment-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ9aUAutFNNJ3oTRRopjAbvTkThNL2k10',
    appId: '1:14399025694:ios:3d887f601d6bcd2454b40f',
    messagingSenderId: '14399025694',
    projectId: 'fare-payment-system',
    storageBucket: 'fare-payment-system.appspot.com',
    iosBundleId: 'com.example.farePaymentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ9aUAutFNNJ3oTRRopjAbvTkThNL2k10',
    appId: '1:14399025694:ios:3d887f601d6bcd2454b40f',
    messagingSenderId: '14399025694',
    projectId: 'fare-payment-system',
    storageBucket: 'fare-payment-system.appspot.com',
    iosBundleId: 'com.example.farePaymentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyL7ztnq4JiE8r9m4QcfiLpMtJAV_CDbg',
    appId: '1:14399025694:web:46d77d0d9bc80f7a54b40f',
    messagingSenderId: '14399025694',
    projectId: 'fare-payment-system',
    authDomain: 'fare-payment-system.firebaseapp.com',
    storageBucket: 'fare-payment-system.appspot.com',
    measurementId: 'G-VQ9VVTZEPS',
  );
}
